### ISSUE TITLE
Fehlerhafte Umbrüche in Abstracts (S)

### ISSUE THREAD

**Issue by mwalter** [SchweizerischeBundesbahnen/conference-buddy#146]
Mir ist aufgefallen, dass einige Abstracts fehlerhafte Textumbrüche enthalten. An den Stellen, wo ein Absatz eingefügt wird, ist aber gar kein p-Tag drin. Zum Beispiel sind Umbrüche in A2 und B2. Betroffen scheint nur die Desktop-Variante zu sein. Auf meinem S4 sieht es gut aus.
Meine Vermutung ist, dass es mit der CollapsibleTextDirective zu tun hat. Scheint sich nicht mit
```
$sce.trustAsHtml()
```
zu vertragen.

**Comment by kguelseven** [comment]
Habe die CollapsibleTexts entfernt. Desktop/Pad-Variante bietet genügend Platz für den gesamten Text. Auf die Schnelle habe ich keine saubere Lösung hingekriegt, bei der der Text nicht auseinander fällt. 
https://github.com/SchweizerischeBundesbahnen/conference-buddy/pull/192
https://github.com/SchweizerischeBundesbahnen/conference-buddy/pull/189
