### ISSUE TITLE
Zeitliche Reihenfolge der Sessions und Pausen

### ISSUE THREAD

**Issue by puce77** [SchweizerischeBundesbahnen/conference-buddy#147]
Die Zeitliche Reihenfolge der Sessions und Pausen sind verschoben. (siehe Bild)
![conference-buddy-zeitliche-abfolge](https://cloud.githubusercontent.com/assets/9258186/5394418/79ca5d5a-813d-11e4-929e-a5c241c0f844.png)

Vermutlicher Grund:
Ich habe mich für keine "A" Session eingetragen, da ich dann selber einen Vortrag gehalten habe.

Das scheint die Pausen verschoben zu haben.

Zunächst dachte ich, das sei ein Windows Phone 7.5 (SBB Phone) Problem, aber das Problem tritt auch im Firefox auf dem Desktop auf.

**Comment by kguelseven** [comment]
Nochmals gut testen.

**Comment by kguelseven** [comment]
Scheint iO zu sein. Zu.
