### ISSUE TITLE
Rating ist nicht readonly

### ISSUE THREAD

**Issue by Stefku** [SchweizerischeBundesbahnen/conference-buddy#165]
Das errechnete Durchschnitts-Rating auf der Details Seite einer Presentation ist nicht readonly.

**Comment by kguelseven** [comment]
Dieses Issue kann ich local nicht reproduzieren, aber unter http://confbuddy.eu-central-1.elasticbeanstalk.com/#/tracks/details. Was der Grund auch immer ist, hier ein anderer Vorschlag: Wir lassen den berechneten Durchschnittswert als "5* (stern)" anzeigen. So kommt niemand auf die Idee, dass dieser Wert nachträglich geändert werden könnte. Was meinst du @mwalter ?
