### ISSUE TITLE
Testszenario (M)

### ISSUE THREAD

**Issue by kguelseven** [SchweizerischeBundesbahnen/conference-buddy#182]
- Szenario definieren
- mit vielen Geräten testen 

Durchführung von explorativem Testing
- https://confluence.sbb.ch/download/attachments/439123976/08_Exploratory_SessionBased_Testing.pdf?version=1&modificationDate=1416553232000&api=v2

**Comment by ncotting** [comment]
Ich bin bereit diesen Task zu übernehmen

**Comment by ncotting** [comment]
Im Confluence Szenarios erstellt
